name: Ubuntu make

on:
  push:
    branches: [ master, development, libov_win ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: fetchtags
      run: git fetch --unshallow --tags
    - name: submodules
      run: git submodule init && git submodule update
    - name: dependencies
      run: sudo apt update &&
           sudo apt install --assume-yes git zita-njbridge liblo-dev nodejs libcurl4-openssl-dev build-essential libasound2-dev libeigen3-dev libfftw3-dev libfftw3-double3 libfftw3-single3 libgsl-dev libjack-jackd2-dev libltc-dev libmatio-dev libsndfile1-dev libsamplerate0-dev libboost-all-dev libxerces-c-dev libcpprest-dev nlohmann-json3-dev libsoundio-dev libgtkmm-3.0-dev libcairomm-1.0-dev libcunit1-dev libsodium-dev
    - name: make
      run: make
    - name: Unit tests
      run: make unit-tests
